name = "PlutoLatexConverter"
uuid = "d1325287-e83a-42c1-9f4a-9cbc16300cd8"
authors = ["Davi Barreira <davisbarreira@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
ReadableRegex = "cbbcb084-453d-4c4c-b292-e315607ba6a4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
