name = "PlutoLatexConverter"
uuid = "d1325287-e83a-42c1-9f4a-9cbc16300cd8"
authors = ["Davi Barreira <davisbarreira@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ReadableRegex = "cbbcb084-453d-4c4c-b292-e315607ba6a4"

[compat]
julia = "1"

[extras]
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots", "Makie", "CairoMakie", "PlutoUI"]
